# Generated by Django 2.1.1 on 2018-09-18 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
