# Generated by Django 2.1.1 on 2018-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_auto_20180918_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='attendance_status',
            new_name='will_attend',
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
