# Generated by Django 2.1.1 on 2018-09-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_auto_20180919_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='todo_list',
            new_name='a_list',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_date',
        ),
    ]
