# Generated by Django 2.1.1 on 2018-09-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_auto_20180919_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='guest',
            field=models.BooleanField(default=False),
        ),
    ]
