# Generated by Django 2.1.1 on 2018-09-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_list_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('an_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.Event')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='list',
            name='guest',
        ),
    ]
